
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-02
owner: ucsb-cs156-f24
repo_name: team01-f24-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjY1ODc1MjE3","is_bot":false,"login":"rushil-x-gupta","name":""},"headRefName":"rg-HelpRequest-create-db","number":48,"title":"rg - created database table for HelpRequest","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/48"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly","number":43,"title":"Created RecommendationRequest table, controller and tests","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/43"}]
