
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-02
owner: ucsb-cs156-f24
repo_name: team01-f24-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjI5Njc5MDYz","is_bot":false,"login":"billybobjoe123","name":""},"headRefName":"billybobjoe123","number":60,"title":"Create database table for articles, Create ArticlesController added GET (index), POST (create) GET(show) PUT(edit) DELETE endpoints","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/60"},{"author":{"id":"MDQ6VXNlcjY1ODc1MjE3","is_bot":false,"login":"rushil-x-gupta","name":""},"headRefName":"rg-HelpRequest-endpoint","number":59,"title":"Created PUT and DELETE endpoints","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/59"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReview-DELETE","number":58,"title":"vp menu item review delete","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/58"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReview-PUT","number":57,"title":"vp menu item review put","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/57"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReview-GET","number":56,"title":"vp menu item review get","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/56"},{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReview-Controller","number":55,"title":"vp menu item review controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/55"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganization-PUT","number":54,"title":"Finished PUT Endpoint for UCSBOrganization, Meeting all Mutations ","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/54"}]
