
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-02
owner: ucsb-cs156-f24
repo_name: team01-f24-02
pull_requests: [{"author":{"id":"U_kgDOBt27wQ","is_bot":false,"login":"vedp3705","name":""},"headRefName":"vp-MenuItemReview-create-db","number":47,"title":"Menu Item Review DB created","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/47"},{"author":{"id":"U_kgDOB3Cn0w","is_bot":false,"login":"EduinoMEH","name":"Edwin E. Medrano Villela"},"headRefName":"eduinomeh-UCSBOrganization-create-db","number":46,"title":"Database Table for UCSB Organization has been completed.","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/46"},{"author":{"id":"U_kgDOBuPHZA","is_bot":false,"login":"leozhu0","name":""},"headRefName":"Leo-UCSBDiningCommonsMenuItems","number":45,"title":"UCSB Dining Commons Menu Items","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/45"},{"author":{"id":"U_kgDOB2W7yQ","is_bot":false,"login":"berdly","name":"Jakob Pinedo"},"headRefName":"berdly","number":43,"title":"Created RecommendationRequest table, controller and tests","url":"https://github.com/ucsb-cs156-f24/team01-f24-02/pull/43"}]
